# ansible/roles/docker/tasks/main.yml
- name: Install Docker dependencies
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

#- name: Add Docker GPG key
#  apt_key:
#    url: https://download.docker.com/linux/ubuntu/gpg
#    state: present

- name: Add Docker repo
  apt_repository:
    repo: "deb https://download.docker.com/linux/ubuntu jammy stable"

- name: Wait for apt lock to be released
  shell: |
    while fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1; do
      sleep 5
    done
  changed_when: false

- name: Disable unattended upgrades
  systemd:
    name: unattended-upgrades
    enabled: false
    state: stopped

- name: Disable apt timers
  systemd:
    name: "{{ item }}"
    enabled: false
    state: stopped
  loop:
    - apt-daily.timer
    - apt-daily-upgrade.timer

- name: Fix broken dpkg state
  command: dpkg --configure -a
  become: true
  ignore_errors: yes

- name: Update apt cache
  apt:
    update_cache: yes
  register: apt_update
  retries: 5
  delay: 10
  until: apt_update is succeeded

- name: Install Docker
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes

- name: Enable Docker
  systemd:
    name: docker
    enabled: yes
    state: started