- name: Ensure .ssh directory exists
  file:
    path: "/home/{{ app_user }}/.ssh"
    state: directory
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0700"

#- name: Check if GitHub key exists
#  stat:
#    path: "/home/{{ app_user }}/.ssh/id_ed25519_github"
#  register: github_key

- name: Fail if key is missing and no source provided
  fail:
    msg: "GitHub key missing and no key provided to install it"
  when:
    - not github_key.stat.exists
    - github_private_key is not defined

- name: Install GitHub private key
  copy:
    content: "{{ github_private_key }}"
    dest: "/home/{{ app_user }}/.ssh/id_ed25519_github"
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"
  when:
    - not github_key.stat.exists
    - github_private_key is defined

- name: Configure SSH for GitHub
  copy:
    dest: "/home/{{ app_user }}/.ssh/config"
    content: |
      Host github.com
        IdentityFile /home/{{ app_user }}/.ssh/id_ed25519_github
        IdentitiesOnly yes
    owner: "{{ app_user }}"
    group: "{{ app_user }}"
    mode: "0600"

- name: Add GitHub to known_hosts
  become_user: "{{ app_user }}"
  known_hosts:
    name: github.com
    key: "{{ lookup('pipe', 'ssh-keyscan github.com') }}"
    path: "/home/{{ app_user }}/.ssh/known_hosts"